### ISSUE TITLE
Fix Linter issues

### ISSUE THREAD

**Issue by Zabuzard** [bowbahdoe/ModernJava#11]
We just added a linter and it reports a lot of issues (obviously):

![linter](https://i.imgur.com/yRBb7hz.png)

We should go through them and fix the issues and adjust the config file to our needs while doing so.

**Comment by bowbahdoe** [comment]
I fixed the markdown lint stuff in #13. When that is merged i'd call it good

**Comment by bowbahdoe** [comment]
Addressed
