### ISSUE TITLE
Write initial documentation

### ISSUE THREAD

**Issue by Zabuzard** [bowbahdoe/ModernJava#2]
The Wiki, currently empty, needs some basic intro pages, such as
* `.../wiki/Contributing`
* a guide how to publish locally (install mdbook, `mdbook serve -open`, link to the docs https://rust-lang.github.io/mdBook/guide/installation.html ...)
* a guide with our writing standards

We also need to adjust the `README.md` file:
* quick intro what it is
* guide for readers
* guide for writers
* entry point to the Wiki ...

**Comment by Taz03** [comment]
y do we need a guide for a guide? (im talking about the mdbook guide)

**Comment by Taz03** [comment]
i can create the guide for locally hosting mdbook, but at where should i start installing cargo, or should i assume that cargo is installed already?

**Comment by Zabuzard** [comment]
* we need a short intro page that tells people what this project is (reflected in README)
* we need a very short guide for readers where they can find the website and how to get started reading the book (in case they jumped to the github instead of the website). it should also tell them quickly how they can edit pages.
* we need guides for writers containing:
  * a CONTRIBUTING page that helps them get started and links them to further resources (first PR, git, ...)
  * how to set up mdbook stuff locally (mdbook install, build, serve, ...)
  * our writing guidelines ("I", "you", modern Java only, present tense, ...
  * the structure of the book and its sections, where to put what kind of article
  * how to setup their local editors according to our CI rules (languagetool, markdownlinter, ...)
* we need guides for maintainers explaining the project structure and how to do maintanence:
  * how to release a new version
  * where to find the configs for the various tools

**Comment by firasrg** [comment]
I'm interested in this issue! however I have some points to tell: 
- I think that this repo is about a book not a website?
- I think this issue is related to #4, right?
- I think, for me, it might be better to focus on the content of the book not the management guides of this project. 

thanks in advance

**Comment by bowbahdoe** [comment]
I updated the README with clearer contribution instructions. This issue is stale so i am gonna close it and make new ones for some of the subtasks here
