### ISSUE TITLE
Auto-deployment to gh-pages

### ISSUE THREAD

**Issue by Zabuzard** [bowbahdoe/ModernJava#3]
Initially, we use **gh-pages** to publish our website (https://together-java.github.io/ModernJava/). This is automatically deployed from the **gh-pages** branch.

Currently, we tried using an existing gh-action that, on pushes to `master`, builds the book and pushes it to the `gh-pages` branch. For some reason, the action fails:

https://github.com/Together-Java/ModernJava/actions/runs/3891853695
![errors](https://i.imgur.com/3Kv2XGS.png)

Either we investigate and fix the action, or we do it ourselves. mdBook actually has a guide for this: https://github.com/rust-lang/mdBook/wiki/Automated-Deployment%3A-GitHub-Pages

But essentially, all that has to be done is:
* download the `mdbook` CLI tool
* run `mdbook build`
* publish the content in `book/` into `gh-pages` (a bit annoying, since the working tree has to be changed to there)

**Comment by Zabuzard** [comment]
@marko-radosavljevic maybe sth for u? 🙂

**Comment by marko-radosavljevic** [comment]
Sure, I can take a look. :relaxed:

**Comment by marko-radosavljevic** [comment]
The new workflow seems to be working well. @Zabuzard 

I will monitor it for a few days, while we test it out properly. ^^

It's using already existing actions, that are being actively maintained:
https://github.com/peaceiris/actions-gh-pages
https://github.com/peaceiris/actions-mdbook

Which is good enough to get us started, but we will probably have to do it manually when we switch to more complex scenarios with mdbook plugins and pipeline tooling.

**Comment by Zabuzard** [comment]
lovely 👍
