### ISSUE TITLE
Fix codebox format

### ISSUE THREAD

**Issue by MrMystery10-del** [bowbahdoe/ModernJava#39]
Pretty much all codeboxes in 'src/boxed_primitives' are not formatted correctly. 

Instead of:
```java
void main() {
     Boolean b = null;
     System.out.println(b);
     b = true;
     System.out.println(true);
}
```
They are formatted without the tab before new line in method body:
```java
void main() {
Boolean b = null;
System.out.println(b);
b = true;
System.out.println(true);
}
```

This is just ugly and bad for readability.

**Comment by MrMystery10-del** [comment]
Opened pull-request for this: #40

**Comment by bowbahdoe** [comment]
This is intentional. Closing with #40
