### ISSUE TITLE
Add initial content structure

### ISSUE THREAD

**Issue by Zabuzard** [bowbahdoe/ModernJava#4]
Before we really get started, we have to add:
* index / TOC
* some example content for some of those pages

and generally finalize the structure we want.

The playground repo for this was: https://github.com/bowbahdoe/javabook

**Comment by firasrg** [comment]
Hello @Zabuzard ! 

I see that the repo is not well organized yet, there are some files and directories with same name which might be confusing. Is it possible to let me take care about the structure of the whole project please? Also I can provide some content and adjustments.

**Comment by bowbahdoe** [comment]
@firasrg - You should direct this to me not @Zabuzard for the moment.

> I see that the repo is not well organized yet

I think we fell behind the original concept of mapping the entire book and then filling it in and I ended up just starting and growing from there. This seems to have been a better approach so maybe this card for "map out the whole book" should be replaced by "get far enough that its possible to speculate out further" or similar.

> there are some files and directories with same name which might be confusing.

Your concern is noted, but these also affect the urls and the same-naming hasn't been a problem for the workflow of adding a section to the summary and ctrl clicking to the generated file so i'm not sure what the fix would even be?

> Is it possible to let me take care about the structure of the whole project please?

no

**Comment by bowbahdoe** [comment]
I'm gonna close this one out
