### ISSUE TITLE
Find and add some useful workflows to the pipeline

### ISSUE THREAD

**Issue by Zabuzard** [bowbahdoe/ModernJava#5]
There are for sure some useful GH-actions workflows out there, which we could add to our pipeline (besides deploying the website).

Some things that come to my mind would be:
- [x] spelling/grammar checking
- [x] markdown validation/linter (sonar? codeql? codefactor? ...)
- [x] markdown formatting (spotless? ...)
- [x] dead link checker
- [ ] (if possibly, some sort of code checking on snippets)
- maybe more?

**Comment by Zabuzard** [comment]
Added a linter. Unfortunately, it doesnt have a super nice UI. But it works.

![linter](https://i.imgur.com/yRBb7hz.png)

**Comment by Zabuzard** [comment]
added a dead-link checker

**Comment by Zabuzard** [comment]
Added a language checker based on LanguageTool

![language](https://i.imgur.com/ZTLOQ07.png)

**Comment by Zabuzard** [comment]
ill see if i can find more useful stuff

**Comment by bowbahdoe** [comment]
These workflows, TBH, have been more of a PITA than anything else. I disabled the markdown lint one since there are way too many things to fix + autoformatting breaks footnotes. Will revisit if it starts to matter more or I start making a ton of meaningful mistakes
