### ISSUE TITLE
Playground Communication: timeout

### ISSUE THREAD

**Issue by iWiggins** [bowbahdoe/ModernJava#59]
When attempting to run examples, the book returns the output `Playground Communication: timeout`.

To reproduce:

1.  Open a runnable example, such as one of those on [this page](https://javabook.mccue.dev/loops_ii/for).
2. Click the run button on the example.
3. The output of the example will not contain the expected output from the code. Instead, it will contain the error message `Playground Communication: timeout`.

**Comment by bowbahdoe** [comment]
@iWiggins had to reboot the machine serving that. If it happens again just make another issue.

Can you tell I don't have a budget?
